/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerPatients;
import Controller.ControllerQueue;
import Controller.ControllerUsers;

import Model.Users.ModelUsers;
import javax.swing.JFrame;
import javax.swing.table.TableModel;
import java.util.LinkedList;
import javax.swing.DefaultListModel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JList;
/**
 *
 * @author Iam
 */
public class AdminDashboard extends javax.swing.JFrame {

    private LinkedList<String> patientQueue = new LinkedList<>();
    private DefaultListModel<String> queueListModel = new DefaultListModel<>();
    private JPanel queuePanel;
    private JTextField queueNameField;
    private JButton addToQueueButton;
    private JList<String> queueList;

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard(ModelUsers user) {
        setTitle("Admin Dashboard");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        table.setModel(ControllerPatients.getTableModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        usersMenuItem = new javax.swing.JMenuItem();
        patientsMenuItem = new javax.swing.JMenuItem();
        queueMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addUserMenuItem = new javax.swing.JMenuItem();
        addPatientsMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jMenu3.setText("Setting");

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(logoutMenuItem);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("View");

        usersMenuItem.setText("Users");
        usersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(usersMenuItem);

        patientsMenuItem.setText("Patients");
        patientsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(patientsMenuItem);

        queueMenuItem.setText("Queue");
        queueMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queueMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(queueMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Add");

        addUserMenuItem.setText("User");
        addUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(addUserMenuItem);

        addPatientsMenuItem.setText("Patients");
        jMenu2.add(addPatientsMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );

    // --- Begin Queue Panel code ---
    queuePanel = new JPanel();
    queuePanel.setLayout(new java.awt.BorderLayout());

    javax.swing.JPanel inputPanel = new javax.swing.JPanel();
    queueNameField = new JTextField(15);
    addToQueueButton = new JButton("Add to Queue");
    inputPanel.add(new javax.swing.JLabel("Patient Name:"));
    inputPanel.add(queueNameField);
    inputPanel.add(addToQueueButton);

    JButton removeFromQueueButton = new JButton("Remove from Queue");
    inputPanel.add(removeFromQueueButton);

    // Add action listener for remove button
    removeFromQueueButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            int selectedIndex = queueList.getSelectedIndex();
            if (selectedIndex != -1) {
                patientQueue.remove(selectedIndex);
                queueListModel.remove(selectedIndex);
            } else if (!patientQueue.isEmpty()) {
                // Remove first if nothing is selected
                patientQueue.removeFirst();
                queueListModel.remove(0);
            }
        }
    });
    
    queueList = new JList<>(queueListModel);
    javax.swing.JScrollPane queueScrollPane = new javax.swing.JScrollPane(queueList);

    queuePanel.add(inputPanel, java.awt.BorderLayout.NORTH);
    queuePanel.add(queueScrollPane, java.awt.BorderLayout.CENTER);

    jTabbedPane1.addTab("Queue Edit", queuePanel);

    addToQueueButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            String name = queueNameField.getText().trim();
            if (!name.isEmpty()) {
                patientQueue.add(name);
                queueListModel.addElement(name);
                queueNameField.setText("");
            }
        }
    });
    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void usersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersMenuItemActionPerformed
        TableModel model = ControllerUsers.getTableModel();
        table.setModel(model);
    }//GEN-LAST:event_usersMenuItemActionPerformed

    private void patientsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsMenuItemActionPerformed
        TableModel model = ControllerPatients.getTableModel();
        table.setModel(model);
    }//GEN-LAST:event_patientsMenuItemActionPerformed

    private void queueMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queueMenuItemActionPerformed
        TableModel model = ControllerQueue.getTableModel();
        table.setModel(model);
    }//GEN-LAST:event_queueMenuItemActionPerformed

    private void addUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModelUsers user = null;
                new AdminDashboard(user).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addPatientsMenuItem;
    private javax.swing.JMenuItem addUserMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem patientsMenuItem;
    private javax.swing.JMenuItem queueMenuItem;
    private javax.swing.JTable table;
    private javax.swing.JMenuItem usersMenuItem;
    // End of variables declaration//GEN-END:variables
}
